In [1]:
import numpy

In [2]:
# crear un array

A = numpy.array([3, 33, 333])
A

array([  3,  33, 333])

In [3]:
type(A)

numpy.ndarray

In [4]:
# ver dimensiones
A.shape

(3,)

In [5]:
A[1]

33

In [6]:
A[0] = 888

In [7]:
A

array([888,  33, 333])

In [10]:
# array 2D: matriz
B = numpy.array([[11,12,13], [21,22,23]])
B

array([[11, 12, 13],
       [21, 22, 23]])

In [11]:
B.shape

(2, 3)

In [14]:
# generar arrays
E1 = numpy.zeros((2, 3))
E1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
E2 = numpy.ones((4,7))
E2I

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [16]:
E3 = numpy.full((4,5), 2.6)
E3

array([[2.6, 2.6, 2.6, 2.6, 2.6],
       [2.6, 2.6, 2.6, 2.6, 2.6],
       [2.6, 2.6, 2.6, 2.6, 2.6],
       [2.6, 2.6, 2.6, 2.6, 2.6]])

In [17]:
# matriz identidad
I = numpy.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
E5 = numpy.random.random((3,2))
E5

array([[0.34446888, 0.8884353 ],
       [0.84140836, 0.9118129 ],
       [0.52148168, 0.02986821]])

In [21]:
# manipulacion de las matrices
A = numpy.array([[11, 12, 13],[21, 22, 23],[31, 32, 33]])
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [22]:
A[:, 0]

array([11, 21, 31])

In [23]:
A[:, 1]

array([12, 22, 32])

In [24]:
A[0, :]

array([11, 12, 13])

In [25]:
A[:2, 1:3]






array([[12, 13],
       [22, 23]])

In [26]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [27]:
A.T

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [28]:
B = numpy.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
B.sum()

45

In [31]:
B.sum(0)

array([12, 15, 18])

In [32]:
B.sum(1)

array([ 6, 15, 24])

In [33]:
B.mean()

5.0

In [34]:
B.std()

2.581988897471611